name: ESET License Key

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      account:
        description: 'Number of Accounts to be generated (default = 1)'
        required: false
        default: '1'
      key:
        description: 'Number of Keys to be generated (default = 1)'
        required: false
        default: '1'

jobs:
  GenerateKey:
    runs-on: ubuntu-latest
    steps:
      - name: Generate key
        run: |
          ACCOUNT=${{ github.event.inputs.account }}
          KEY=${{ github.event.inputs.key }}
          git clone https://github.com/rzc0d3r/ESET-KeyGen.git
          cd ESET-KeyGen
          sudo apt update
          sudo apt install python3-pip
          sudo pip install -r requirements.txt
          if [[ ${ACCOUNT} != 0 ]]
          then
          for ((attempt=1;attempt<=${ACCOUNT};++attempt))
          do
          sudo python3 main.py --account --cli
          done
          echo "Account:" >> $GITHUB_STEP_SUMMARY
          cat ./*ACCOUNTS.txt >> $GITHUB_STEP_SUMMARY
          fi
          if [[ ${KEY} != 0 ]]
          then
          for ((attempt=1;attempt<=${KEY};++attempt))
          do
          sudo python3 main.py --cli
          done
          echo -e "\nKey:" >> $GITHUB_STEP_SUMMARY
          cat ./*KEYS.txt >> $GITHUB_STEP_SUMMARY
          fi
